CarTARge22/Models/Cars/CarsCreateUdateVIewModel.cs
namespace CarTARge22.Models.Cars
{
    public class CarsCreateUdateVIewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public DateTime Year { get; set; }
        public TransmissionType Transmission { get; set; }
        public string Color { get; set; }
        public string Fuel { get; set; }
        public int TopSpeed { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }

    public enum TransmissionType
    {
        Manual,
        Automatic,
        Default
    }
}

CarTARge22/Models/Cars/CarsDeleteViewModel.cs
namespace CarTARge22.Models.Cars
{
    public class CarsDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public DateTime Year { get; set; }
        public string Transmission { get; set; }

        public string Color { get; set; }
        public string Fuel { get; set; }
        public int TopSpeed { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

CarTARge22/Models/Cars/CarsDetailsViewModel.cs
namespace CarTARge22.Models.Cars
{
    public class CarsDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public DateTime Year { get; set; }
        public string Transmission { get; set; }

        public string Color { get; set; }
        public string Fuel { get; set; }
        public int TopSpeed { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

CarTARge22/Models/Cars/CarsIndexViewModel.cs
namespace CarTARge22.Models.Cars
{
    public class CarsIndexViewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public DateTime Year { get; set; }
        public string Transmission {  get; set; }

    }
}

CarTARge22/Models/ErrorViewModel.cs
namespace CarTARge22.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CarTARge22/Controllers/CarsController.cs
using CarTARge22.Core.Dto;
using CarTARge22.Core.ServiceInterface;
using CarTARge22.Data;
using CarTARge22.Models.Cars;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;
using TransmissionType = CarTARge22.Core.Dto.TransmissionType;

namespace CarTARge22.Controllers
{
    public class CarsController : Controller
    {
        private readonly CarTARge22Context _context;
        private readonly ICarsServices _carsServices;

        public CarsController
            (
            CarTARge22Context context,
            ICarsServices carsServices
            )
        {
            _context = context;
            _carsServices = carsServices;
        }
        public IActionResult Index()
        {
            var result = _context.Cars
                .Select(x => new CarsIndexViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    Brand = x.Brand,
                    Year = x.Year,
                    Transmission = x.Transmission,
                });
            return View(result);
        }



        [HttpGet]
        public IActionResult Create()
        {
            CarsCreateUdateVIewModel result = new CarsCreateUdateVIewModel();
            return View("CreateUpdate", result);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CarsCreateUdateVIewModel vm)
        {
            var dto = new CarDto()
            {
                Id = vm.Id,
                Name = vm.Name,
                Brand = vm.Brand,
                Year = vm.Year,
                Transmission = (TransmissionType)vm.Transmission,
                Color = vm.Color,
                Fuel = vm.Fuel,
                TopSpeed = vm.TopSpeed,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt
            };
            var result = await _carsServices.Create(dto);
            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var car = await _carsServices.DetailsAsync(id);

            if (car == null)
            {
                return NotFound();
            }

            var vm = new CarsDetailsViewModel();
            vm.Id = id;
            vm.Name = car.Name;
            vm.Brand = car.Brand;
            vm.Year = car.Year;
            vm.Transmission = car.Transmission;
            vm.Color = car.Color;
            vm.Fuel = car.Fuel;
            vm.TopSpeed = car.TopSpeed;
            vm.CreatedAt = car.CreatedAt;
            vm.ModifiedAt = car.ModifiedAt;

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var car = await _carsServices.DetailsAsync(id);

            if (car == null)
            {
                return NotFound();
            }

            var vm = new CarsCreateUdateVIewModel();
            vm.Id = id;
            vm.Name = car.Name;
            vm.Brand = car.Brand;
            vm.Year = car.Year;
            if (Enum.TryParse(typeof(TransmissionType), car.Transmission, out var transmission))
            {
                vm.Transmission = (Models.Cars.TransmissionType)(TransmissionType)transmission;
            }
            else
            {
                return NotFound();
            }
            vm.Color = car.Color;
            vm.Fuel = car.Fuel;
            vm.TopSpeed = car.TopSpeed;
            vm.CreatedAt = car.CreatedAt;
            vm.ModifiedAt = car.ModifiedAt;

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(CarsCreateUdateVIewModel vm)
        {
            var dto = new CarDto()
            {
                Id = vm.Id,
                Name = vm.Name,
                Brand = vm.Brand,
                Year = vm.Year,
                Transmission = (TransmissionType)vm.Transmission,
                Color = vm.Color,
                Fuel = vm.Fuel,
                TopSpeed = vm.TopSpeed,

                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
            };
            var result = await _carsServices.Update(dto);
            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index), vm);

        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var car = await _carsServices.DetailsAsync(id);

            if (car == null)
            {
                return NotFound();
            }

            var vm = new CarsDeleteViewModel();

            vm.Id = car.Id;
            vm.Name = car.Name;
            vm.Brand = car.Brand;
            vm.Year = car.Year;
            vm.Transmission = car.Transmission;
            vm.Color = car.Color;
            vm.Fuel = car.Fuel;
            vm.TopSpeed = car.TopSpeed;
            vm.CreatedAt = car.CreatedAt;
            vm.ModifiedAt = car.ModifiedAt;

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var carId = await _carsServices.Delete(id);

            if (carId == null)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CarTARge22/Controllers/HomeController.cs
using CarTARge22.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CarTARge22.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CarTARge22/Views/Cars/CreateUpdate.cshtml
@using CarTARge22.Models.Cars;
@model CarTARge22.Models.Cars.CarsCreateUdateVIewModel

@if(Model.Id.HasValue)
{
    <header class="major">
        <h2 style="padding: 20px;"> UPDATE</h2>
    </header>
}
else
{
    <header class="major">
        <h2 style="padding: 20px;"> CREATE</h2>
    </header>
}

<body style="background-image:url(https://images.pexels.com/photos/845406/pexels-photo-845406.jpeg); background-size:cover; opacity: 0.8;">

<section>
    <div style="padding: 20px; text-align: center; padding: 5%">
        <form method="post" enctype="multipart/form-data">
            <input asp-for="Id" type="hidden" />
            <input asp-for="CreatedAt" type="hidden" />
            <input asp-for="ModifiedAt" type="hidden" />

            <div class="form-group row">
                <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-5">
                    <input asp-for="Name" class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="Brand" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-5">
                    <input asp-for="Brand" class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="Year" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-5">
                    <input asp-for="Year" class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="Transmission" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-5">
                        <select asp-for="Transmission" class="form-control">
                            @foreach (var value in Enum.GetValues(typeof(TransmissionType)))
                            {
                                <option value="@value">@value</option>
                            }
                        </select>
                    </div>
            </div>

            <div class="form-group row">
                <label asp-for="Color" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-5">
                    <input asp-for="Color" class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="Fuel" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-5">
                    <input asp-for="Fuel" class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="TopSpeed" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-5">
                    <input asp-for="TopSpeed" class="form-control" />
                </div>
            </div>

            <hr/>
            @if(Model.Id.HasValue)
            {
                    <input asp-action="update" asp-controller="cars" type="submit" class="btn" style="background-color: greenyellow; padding: 10px 20px" value="Create" />
            }

            else
            {
                    <input asp-action="create" asp-controller="cars" type="submit" class="btn" style="background-color: greenyellow; padding: 10px 20px" value="Create" />

            }
            <a asp-action="index" class="btn" style="background-color:salmon; padding: 10px 20px">Index</a>

        </form>
    </div>
</section>
</body>

CarTARge22/Views/Cars/Delete.cshtml
@model CarTARge22.Models.Cars.CarsDeleteViewModel

<header class="major" style="padding: 20px;">
    <h2 > DELETE</h2>
    <h3 style="color:white;">There is no going back. Are you sure?</h3>
</header>

<body style="background-image:url(https://images.pexels.com/photos/754595/pexels-photo-754595.jpeg); background-size:cover; opacity: 0.8;">
    <div style="padding: 20px; text-align: center; padding: 5%; color: white;">
            <dl class="row">
            <div class="form-group row">
                <label asp-for="Id" class="col-sm-2 col-form-label"></label> 
                @Html.DisplayFor(model => model.Id)
            </div>

            <div class="form-group row">
                <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Name)
            </div>

            <div class="form-group row">
                <label asp-for="Brand" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Brand)
            </div>

            <div class="form-group row">
                <label asp-for="Year" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Year)
            </div>

            <div class="form-group row">
                <label asp-for="Transmission" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Transmission)
            </div>

            <div class="form-group row">
                <label asp-for="Color" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Color)
            </div>

            <div class="form-group row">
                <label asp-for="Fuel" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Fuel)
            </div>

            <div class="form-group row">
                <label asp-for="TopSpeed" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.TopSpeed)
            </div>

            <div class="form-group row">
                <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.CreatedAt)
            </div>

            <div class="form-group row">
                <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.ModifiedAt)
            </div>
        </dl>

        <form asp-action="DeleteConfirmation">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn" style="background-color:rebeccapurple; padding: 10px 20px; color:white;" />
            <a asp-action="Index" asp-controller="cars" class="btn" style="background-color:palevioletred; padding: 10px 20px; color:white">Back</a>
        </form>
    </div>
</body>

CarTARge22/Views/Cars/Details.cshtml
@model CarTARge22.Models.Cars.CarsDetailsViewModel

<header class="major">
    <h2 style="padding: 20px;"> DETAILS</h2>
</header>

<body style="background-image:url(https://images.pexels.com/photos/226460/pexels-photo-226460.jpeg); background-size:cover; opacity: 0.8;">
    <div style="padding: 20px; text-align: left; padding: 5%;">

        <dl class="row">
            <div class="form-group-row">
                <label asp-for="Id" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Id)
            </div>

            <div class="form-group-row">
                <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Name)
            </div>

            <div class="form-group-row">
                <label asp-for="Brand" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Brand)
            </div>

            <div class="form-group-row">
                <label asp-for="Year" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Year)
            </div>

            <div class="form-group-row">
                <label asp-for="Transmission" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Transmission)
            </div>

            <div class="form-group-row">
                <label asp-for="Color" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Color)
            </div>
            <div class="form-group-row">
                <label asp-for="Fuel" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.Fuel)
            </div>
            <div class="form-group-row">
                <label asp-for="TopSpeed" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.TopSpeed)
            </div>
            <div class="form-group-row">
                <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.CreatedAt)
            </div>
            <div class="form-group-row">
                <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
                @Html.DisplayFor(model => model.ModifiedAt)
            </div>
        </dl>
        <a asp-action="Index" asp-controller="cars" class="btn" style="background-color:mediumaquamarine; padding: 10px 20px">Back</a>
    </div>

</body>

CarTARge22/Views/Cars/Index.cshtml
@model IEnumerable<CarTARge22.Models.Cars.CarsIndexViewModel>

    @{
        int rowNumber = 1;
    }

<body style="background-image: url(https://images.pexels.com/photos/386025/pexels-photo-386025.jpeg); background-size:cover; opacity: 0.8;">
    <div style="padding: 20px">
    <form method="post" class="form" style="padding: 30px;">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Nr</th>
                    <th scope="col">Name</th>
                    <th scope="col">Brand</th>
                    <th scope="col">Year</th>
                    <th scope="col">Transmission</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var cars in Model)
                    {
                        <tr>
                            <td>@rowNumber</td>
                            <td>@cars.Name</td>
                            <td>@cars.Brand</td>
                            <td>@cars.Year</td>
                            <td>@cars.Transmission</td>
                            <td>
                                <a asp-action="details" asp-controller="cars" asp-route-id="@cars.Id" class="btn btn-success">Details</a>
                                <a asp-action="update" asp-controller="cars" asp-route-id="@cars.Id" class="btn btn-warning">Update</a>
                                <a asp-action="delete" asp-controller="cars" asp-route-id="@cars.Id" class="btn btn-danger">Delete</a>
                            </td>
                        </tr>
                        rowNumber += 1;
                    }
                }
                else
                {
                    <p>No data</p>
                }
            </tbody>
        </table>
    </form>
    <div style="padding-left:5%;">
            <a asp-action="create" asp-controller="cars" type="submit" class="btn" style="background-color:#F5CB9F; padding: 10px 20px; font-weight: 800">CREATE</a>

    </div>

</body>

CarTARge22/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is a project CarTARge22</p>
    <body class="main" style="background-image:url(https://images.pexels.com/photos/56832/road-asphalt-space-sky-56832.jpeg); background-size:cover; opacity: 0.8;">

    </body>
</div>

CarTARge22/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarTARge22</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarTARge22.styles.css" asp-append-version="true" />
</head>
    <header>
        <nav class="navbar navbar-expand-lg navbar-scroll">
            <div class="container">
                <li class="nav-item active" style="list-style-type:none">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="text-align:center;">CarTARge22</a>
                </li>
                <img src="https://img.freepik.com/free-vector/vehicle_53876-34800.jpg?w=740&t=st=1703333508~exp=1703334108~hmac=d3ebece8a5a9c9253b427afd237e5c65294aea585008b92dafb6eb6852b227fc" height="70" alt=""
                     loading="lazy" />
                
                <button class="navbar-toggler ps-0" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarExample01"
                        aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon d-flex justify-content-start align-items-center">
                        <i class="fas fa-bars"></i>
                    </span>
                </button>
                <div class="navbar">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Cars" asp-action="Index">Cars</a>
                        </li>

                    </ul>

                    <ul class="navbar-nav flex-row">
                        <li class="nav-item">
                            <a class="nav-link px-2" href="#!">
                                <i class="fab fa-facebook-square"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-2" href="#!">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link ps-2" href="#!">
                                <i class="fab fa-youtube"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <body>
    <div class="flex-container">
            <div class="content">
            @RenderBody()
        </div>
    </div>
    </body>

    <footer class="footer" style="position:fixed;">
        <div class="container">
            &copy; 2023 - CarTARge22 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</html>